controller_list:
  - name: fake_robot_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint 1
      - joint 2
      - joint 3
      - joint 4
      - joint 5
  - name: fake_robot_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - joint 6
initial:  # Define initial robot poses per group
#  - group: robot_arm
#    pose: home

  []